import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

test('Tutorial scene preview mounts source map layers, source camera, and source actor without generic quick-match code', () => {
  const page = fs.readFileSync(new URL('../tutorial-scene-preview.html', import.meta.url), 'utf8');
  const script = fs.readFileSync(new URL('../src/tutorial-scene-preview.mjs', import.meta.url), 'utf8');
  assert.match(page, /<canvas id="tutorialScene" width="800" height="600"/);
  assert.match(page, /src="src\/tutorial-scene-preview\.mjs"/);
  assert.match(script, /getMapVisual\('tut'\)/);
  assert.match(script, /loadMapLayers/);
  assert.match(script, /loadTutorialWorld/);
  assert.match(script, /applyCampaignOneSessionFrame/);
  assert.match(script, /advanceCampaignOneSessionAi/);
  assert.match(script, /advanceCampaignOneSessionAiMovement/);
  assert.match(script, /advanceCampaignOneSessionAiGuns/);
  assert.match(script, /applyTutorialFootContact/);
  assert.match(script, /stepTutorialMovement/);
  assert.match(script, /canvas\.addEventListener\('mouseup'/);
  assert.match(script, /tutorialPlayerMouseDown\(gunState/);
  assert.match(script, /tutorialPlayerMouseUp\(gunState\)/);
  assert.match(script, /advanceTutorialGunRuntime\(gunState/);
  assert.match(script, /traceTutorialLineBullet/);
  assert.match(script, /applyTutorialLineBulletHit/);
  assert.match(script, /applyCampaignOneSessionDeath/);
  assert.match(script, /renderTutorialLineBullet/);
  assert.match(script, /applyTutorialBulletEnvironmentHit/);
  assert.match(script, /units:\s*session\.actors/);
  assert.match(script, /corpses:\s*session\.corpses/);
  assert.match(script, /shooter:\s*sourcePlayer/);
  assert.match(script, /if \(hitOutcome\.died\) applyCampaignOneSessionDeath\(session/);
  assert.match(script, /unit:\s*\{\s*aim:\s*player\.sourcePlayerProfile\.aim/);
  assert.match(script, /ammoMultiplier:\s*player\.sourcePlayerProfile\.ammo/);
  assert.match(script, /canvasPointToTutorialStage/);
  assert.match(script, /tutorialArenaPointer/);
  assert.match(script, /advanceTutorialPlayerAim/);
  assert.match(script, /deriveTutorialUnitAim/);
  assert.match(script, /getTutorialUnitOverheadBar/);
  assert.match(script, /unit-bar-670\.png/);
  assert.match(script, /renderTutorialUnitOverheadBar\(sourcePlayer/);
  assert.match(script, /renderTutorialUnitOverheadBar\(sourceActor/);
  assert.match(script, /globalCompositeOperation = 'source-in'/);
  assert.match(script, /canvas\.addEventListener\('mousemove'/);
  assert.match(script, /advanceTutorialActorPlayback\(actorState, source, \{ advanceArm: !gunTick\.fired \}\)/);
  assert.match(script, /canvas\.addEventListener\('mousedown'/);
  assert.match(script, /beginTutorialActorGunAction\(actorState, gunTick\.action\)/);
  assert.match(script, /requestTutorialActorMotion/);
  assert.match(script, /addEventListener\('keydown'/);
  assert.match(script, /tutorialWorld\.wall/);
  assert.match(script, /advanceTutorialArenaPosition/);
  assert.match(script, /createTutorialActorPlayback/);
  assert.match(script, /beginTutorialActorGunAction/);
  assert.match(script, /createTutorialGunRuntime/);
  assert.match(script, /advanceTutorialGunRuntime/);
  assert.match(script, /tutorialPlayerMouseDown/);
  assert.match(script, /tutorialPlayerMouseUp/);
  assert.match(script, /synchronizeTutorialActorWeapon/);
  assert.match(script, /player\.guns\.active === 'USP2'/);
  assert.match(script, /drawTutorialUnitPose/);
  assert.match(script, /sceneActorStates/);
  assert.match(script, /sceneActorAimStates/);
  assert.match(script, /createTutorialActorPlayback\(binding\)/);
  assert.match(script, /sourceActor\.visible/);
  assert.match(script, /sourceActor\.dead/);
  assert.match(script, /advanceTutorialActorPlayback\(sceneActorState, source\)/);
  assert.match(script, /requestTutorialActorMotion\(sceneActorState, movement\.nextAnim\)/);
  assert.match(script, /beginTutorialActorGunAction\(sceneActorState, gun\.action\)/);
  assert.match(script, /shooter:\s*sourceActor/);
  assert.match(script, /sampleTutorialActorPlayback\(sceneActorState, source, \{ aim: sceneActorAimStates\.get\(sourceActor\.id\) \}\)/);
  assert.match(script, /canvas\.dataset\.ready = 'true'/);
  assert.match(script, /function reportTutorialSceneFailure\(reason\)/);
  assert.match(script, /catch \(reason\) \{\s*reportTutorialSceneFailure\(reason\);/);
  assert.doesNotMatch(script, /main\.mjs|engine\.mjs|createWorld|foundry/);
});
