// GENERATED from assets/reverse/ffdec-deep-20260720/scripts/Stats_Guns.as.
// Regenerate with: npm run generate:guns
export const SOURCE_GUNS = Object.freeze([
  {
    "type": 0,
    "id": "USP",
    "sprite": "USP",
    "name": "USP",
    "typeName": "Pistol",
    "levelRequired": 1,
    "damage": 15,
    "force": 3,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 5,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_pistolFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Uzi",
    "sprite": "Uzi",
    "name": "Uzi",
    "typeName": "Machine-Pistol",
    "levelRequired": 3,
    "damage": 6,
    "force": 3,
    "splash": 0,
    "clipSize": 18,
    "clipSpare": 4,
    "range": 40,
    "recoil": 7,
    "autoFire": true,
    "shootDelay": 0.12,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "mpistol",
      "fire": "mpistol",
      "reload": "mpistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "MP5",
    "sprite": "MP5",
    "name": "MP5",
    "typeName": "SMG",
    "levelRequired": 7,
    "damage": 8,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 54,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.16,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_mp5",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Beretta",
    "sprite": "Beretta",
    "name": "Beretta",
    "typeName": "Pistol",
    "levelRequired": 9,
    "damage": 21,
    "force": 3,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 5,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Skorpion",
    "sprite": "Skorpion",
    "name": "Skorpion",
    "typeName": "Machine-Pistol",
    "levelRequired": 13,
    "damage": 7,
    "force": 3,
    "splash": 0,
    "clipSize": 22,
    "clipSpare": 4,
    "range": 38,
    "recoil": 6,
    "autoFire": true,
    "shootDelay": 0.09,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_pistolFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Vector",
    "sprite": "Vector",
    "name": "Vector",
    "typeName": "SMG",
    "levelRequired": 15,
    "damage": 9,
    "force": 3,
    "splash": 0,
    "clipSize": 32,
    "clipSpare": 3,
    "range": 50,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.12,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Socom",
    "sprite": "Socom",
    "name": "Socom",
    "typeName": "Pistol",
    "levelRequired": 18,
    "damage": 27,
    "force": 5,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 5,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Patriot",
    "sprite": "Patriot",
    "name": "Patriot",
    "typeName": "Machine-Pistol",
    "levelRequired": 21,
    "damage": 10,
    "force": 3,
    "splash": 0,
    "clipSize": 16,
    "clipSpare": 4,
    "range": 42,
    "recoil": 7,
    "autoFire": true,
    "shootDelay": 0.12,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "mpistol",
      "fire": "mpistol",
      "reload": "mpistol"
    },
    "shotSound": "S_pistolFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "UMP",
    "sprite": "UMP",
    "name": "UMP",
    "typeName": "SMG",
    "levelRequired": 24,
    "damage": 15,
    "force": 3,
    "splash": 0,
    "clipSize": 32,
    "clipSpare": 3,
    "range": 58,
    "recoil": 4,
    "autoFire": true,
    "shootDelay": 0.19,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_mp5",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "M1911",
    "sprite": "M1911",
    "name": "M1911",
    "typeName": "Pistol",
    "levelRequired": 27,
    "damage": 36,
    "force": 8,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 5,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_ar2",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Glock 18",
    "sprite": "Glock 18v",
    "name": "Glock 18",
    "typeName": "Machine-Pistol",
    "levelRequired": 30,
    "damage": 11,
    "force": 3,
    "splash": 0,
    "clipSize": 22,
    "clipSpare": 4,
    "range": 40,
    "recoil": 8,
    "autoFire": true,
    "shootDelay": 0.1,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "mpistol",
      "fire": "mpistol",
      "reload": "mpistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Phantom",
    "sprite": "Phantom",
    "name": "Phantom",
    "typeName": "SMG",
    "levelRequired": 33,
    "damage": 13,
    "force": 3,
    "splash": 0,
    "clipSize": 32,
    "clipSpare": 3,
    "range": 52,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.14,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_assaultFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "P99",
    "sprite": "P99",
    "name": "P99",
    "typeName": "Pistol",
    "levelRequired": 35,
    "damage": 42,
    "force": 10,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 5,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Raffica",
    "sprite": "Raffica",
    "name": "Raffica",
    "typeName": "Machine-Pistol",
    "levelRequired": 37,
    "damage": 14,
    "force": 3,
    "splash": 0,
    "clipSize": 18,
    "clipSpare": 4,
    "range": 42,
    "recoil": 7,
    "autoFire": true,
    "shootDelay": 0.12,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "mpistol",
      "fire": "mpistol",
      "reload": "mpistol"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "AKS",
    "sprite": "AKS",
    "name": "AKS 74",
    "typeName": "SMG",
    "levelRequired": 39,
    "damage": 18,
    "force": 3,
    "splash": 0,
    "clipSize": 32,
    "clipSpare": 3,
    "range": 56,
    "recoil": 4,
    "autoFire": true,
    "shootDelay": 0.19,
    "xOffset": 8,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Desert Eagle",
    "sprite": "Desert Eagle",
    "name": "Desert Eagle",
    "typeName": "Pistol",
    "levelRequired": 41,
    "damage": 58,
    "force": 15,
    "splash": 0,
    "clipSize": 7,
    "clipSpare": 5,
    "range": 68,
    "recoil": 4,
    "autoFire": false,
    "shootDelay": 0.3,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_deagle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": "Point five-oh."
  },
  {
    "type": 0,
    "id": "RCP 90",
    "sprite": "RCP 90",
    "name": "RCP 90",
    "typeName": "SMG",
    "levelRequired": 43,
    "damage": 18,
    "force": 3,
    "splash": 0,
    "clipSize": 50,
    "clipSpare": 3,
    "range": 50,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.16,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "bullpup",
      "fire": "bullpup",
      "reload": "bullpup"
    },
    "shotSound": "S_rifle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 0,
    "id": "Cyclone",
    "sprite": "Cyclone",
    "name": "Cyclone",
    "typeName": "Machine-Pistol",
    "levelRequired": 50,
    "damage": 48,
    "force": 10,
    "splash": 40,
    "clipSize": 18,
    "clipSpare": 3,
    "range": 60,
    "recoil": 9,
    "autoFire": true,
    "shootDelay": 0.22,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "gas_small",
      "hit": "explosionSmall",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "mpistol",
      "fire": "mpistol",
      "reload": "mpistol"
    },
    "shotSound": "S_ripperFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Basic",
    "parameters": [
      "ember",
      8,
      0.5
    ],
    "extra": {},
    "description": "It shoots mini explosives!"
  },
  {
    "type": 1,
    "id": "M4",
    "sprite": "M4",
    "name": "M4",
    "typeName": "Assault Rifle",
    "levelRequired": 1,
    "damage": 10,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 60,
    "recoil": 4,
    "autoFire": true,
    "shootDelay": 0.15,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_ar2",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Needler",
    "sprite": "Needler",
    "name": "Needler",
    "typeName": "Magnum",
    "levelRequired": 2,
    "damage": 30,
    "force": 3,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 70,
    "recoil": 4,
    "autoFire": false,
    "shootDelay": 0.28,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_aug",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16737792,
      0.3,
      1.5,
      16737792,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Famas",
    "sprite": "Famas",
    "name": "Famas",
    "typeName": "Assault Rifle",
    "levelRequired": 6,
    "damage": 18,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 78,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.18,
    "xOffset": 8,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "bullpup",
      "fire": "bullpup",
      "reload": "bullpup"
    },
    "shotSound": "S_assaultFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Cougar",
    "sprite": "Cougar",
    "name": "Cougar",
    "typeName": "Magnum",
    "levelRequired": 8,
    "damage": 42,
    "force": 3,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 60,
    "recoil": 4,
    "autoFire": false,
    "shootDelay": 0.35,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_sniperFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Scar",
    "sprite": "Scar",
    "name": "Scar",
    "typeName": "Assault Rifle",
    "levelRequired": 11,
    "damage": 20,
    "force": 3,
    "splash": 0,
    "clipSize": 22,
    "clipSpare": 3,
    "range": 70,
    "recoil": 6,
    "autoFire": true,
    "shootDelay": 0.18,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_elite",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "p357",
    "sprite": "p357",
    "name": "357",
    "typeName": "Magnum",
    "levelRequired": 14,
    "damage": 46,
    "force": 7,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 64,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_sniperFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "G36",
    "sprite": "G36",
    "name": "G36",
    "typeName": "Assault Rifle",
    "levelRequired": 17,
    "damage": 18,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 60,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.15,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_rifle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Colt 45",
    "sprite": "Colt 45",
    "name": "Colt 45",
    "typeName": "Magnum",
    "levelRequired": 20,
    "damage": 58,
    "force": 10,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 70,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.35,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_deagle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "Dragon",
    "sprite": "Dragon",
    "name": "Dragon",
    "typeName": "Assault Rifle",
    "levelRequired": 23,
    "damage": 30,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 90,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.18,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_elite",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "p44",
    "sprite": "p44",
    "name": ".44",
    "typeName": "Magnum",
    "levelRequired": 26,
    "damage": 67,
    "force": 10,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 82,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.4,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_deagle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "AK 47",
    "sprite": "AK 47",
    "name": "AK 47",
    "typeName": "Assault Rifle",
    "levelRequired": 29,
    "damage": 24,
    "force": 3,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 46,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.15,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "arifle"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "rifle"
    },
    "shotSound": "S_ak",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 1,
    "id": "p500",
    "sprite": "p500",
    "name": "500",
    "typeName": "Magnum",
    "levelRequired": 32,
    "damage": 80,
    "force": 20,
    "splash": 0,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 84,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 10,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "magnum"
    },
    "animation": {
      "idle": "magnum",
      "fire": "magnum",
      "reload": "magnum"
    },
    "shotSound": "S_autoshotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 2,
    "id": "Scout",
    "sprite": "Scout",
    "name": "Scout",
    "typeName": "Sniper",
    "levelRequired": 1,
    "damage": 60,
    "force": 3,
    "splash": 0,
    "clipSize": 3,
    "clipSpare": 3,
    "range": 250,
    "recoil": 1,
    "autoFire": false,
    "shootDelay": 0.6,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "sniper"
    },
    "shotSound": "S_sniperFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Sniper",
    "parameters": [
      true,
      3.5,
      13421772,
      0.3,
      1.5,
      15658734,
      0.6
    ],
    "extra": {
      "headDmg": 0.4
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "Knife",
    "sprite": "Knife",
    "name": "Combat Knife",
    "typeName": "Melee",
    "levelRequired": 2,
    "damage": 50,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 6,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "knife",
      "fire": "knife",
      "reload": "knife"
    },
    "shotSound": "S_Whip1",
    "hitSound": "S_Cut3",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0.4,
      "criticalDmg": 0.1,
      "noAmmo": true
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "Barrett",
    "sprite": "Barrett",
    "name": "Barrett",
    "typeName": "Sniper",
    "levelRequired": 6,
    "damage": 65,
    "force": 3,
    "splash": 0,
    "clipSize": 5,
    "clipSpare": 2,
    "range": 250,
    "recoil": 5,
    "autoFire": false,
    "shootDelay": 0.4,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "rifle"
    },
    "shotSound": "S_scout",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Sniper",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 1,
      "headDmg": 0
    },
    "description": "Very heavy, not best to run around with."
  },
  {
    "type": 2,
    "id": "Bat",
    "sprite": "Bat",
    "name": "Bat",
    "typeName": "Melee",
    "levelRequired": 8,
    "damage": 85,
    "force": 100,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 8,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "sword",
      "fire": "sword",
      "reload": "sword"
    },
    "shotSound": "S_Whip2",
    "hitSound": "S_Blunt2",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0,
      "criticalDmg": 0.5,
      "noAmmo": true
    },
    "description": "Knock 'em out of the park!"
  },
  {
    "type": 2,
    "id": "Jackal",
    "sprite": "Jackal",
    "name": "Jackal",
    "typeName": "Sniper",
    "levelRequired": 11,
    "damage": 70,
    "force": 3,
    "splash": 0,
    "clipSize": 2,
    "clipSpare": 8,
    "range": 250,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 0.3,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "sniper"
    },
    "shotSound": "S_sniper",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      2.5,
      13421772,
      0.3,
      1.5,
      13421772,
      0.6
    ],
    "extra": {
      "vision": 0.9,
      "headDmg": 0.3
    },
    "description": "The lightweight Jackal allows for unparalleled accuracy."
  },
  {
    "type": 2,
    "id": "Baton",
    "sprite": "Baton",
    "name": "Baton",
    "typeName": "Melee",
    "levelRequired": 14,
    "damage": 65,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 6,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "knife",
      "fire": "knife",
      "reload": "knife"
    },
    "shotSound": "S_Whip1",
    "hitSound": "S_Blunt2",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0.2,
      "criticalDmg": 0.3,
      "noAmmo": true
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "Dragunov",
    "sprite": "Dragunov",
    "name": "Dragunov",
    "typeName": "Sniper",
    "levelRequired": 17,
    "damage": 90,
    "force": 3,
    "splash": 0,
    "clipSize": 3,
    "clipSpare": 3,
    "range": 250,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.6,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "rifle"
    },
    "shotSound": "S_autoshotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Sniper",
    "parameters": [
      true,
      3.5,
      13421772,
      0.3,
      1.5,
      15658734,
      0.6
    ],
    "extra": {
      "vision": 1,
      "headDmg": 0.4
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "Nine Iron",
    "sprite": "Nine Iron",
    "name": "Nine Iron",
    "typeName": "Melee",
    "levelRequired": 20,
    "damage": 110,
    "force": 100,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 8,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "sword",
      "fire": "sword",
      "reload": "sword"
    },
    "shotSound": "S_Whip2",
    "hitSound": "S_Blunt2",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0,
      "criticalDmg": 0.5,
      "noAmmo": true
    },
    "description": "FORE!"
  },
  {
    "type": 2,
    "id": "Crossbow",
    "sprite": "Crossbow",
    "name": "Crossbow",
    "typeName": "Sniper",
    "levelRequired": 23,
    "damage": 85,
    "force": 10,
    "splash": 0,
    "clipSize": 1,
    "clipSpare": 15,
    "range": 250,
    "recoil": 1,
    "autoFire": false,
    "shootDelay": 0.6,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "rocket"
    },
    "shotSound": "S_ripperFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      2.5,
      6697728,
      0.3,
      1.5,
      6697728,
      0.6
    ],
    "extra": {
      "vision": 1,
      "headDmg": 1.5
    },
    "description": "Poison tipped bolts are extremely deadly, but can't penetrate body armor properly."
  },
  {
    "type": 2,
    "id": "Machete",
    "sprite": "Machete",
    "name": "Machete",
    "typeName": "Melee",
    "levelRequired": 26,
    "damage": 90,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 6,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "knife",
      "fire": "knife",
      "reload": "knife"
    },
    "shotSound": "S_Whip1",
    "hitSound": "S_Cut3",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0.3,
      "criticalDmg": 0.2,
      "noAmmo": true
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "AWP",
    "sprite": "AWP",
    "name": "AWP",
    "typeName": "Sniper",
    "levelRequired": 29,
    "damage": 160,
    "force": 20,
    "splash": 0,
    "clipSize": 1,
    "clipSpare": 5,
    "range": 250,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.9,
    "xOffset": 15,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "sniper"
    },
    "animation": {
      "idle": "sniper",
      "fire": "sniper",
      "reload": "rifle"
    },
    "shotSound": "S_scout",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Sniper",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 1,
      "headDmg": 0.2
    },
    "description": ""
  },
  {
    "type": 2,
    "id": "Katana",
    "sprite": "Katana",
    "name": "Katana",
    "typeName": "Melee",
    "levelRequired": 32,
    "damage": 150,
    "force": 20,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 8,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.45,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "sword",
      "fire": "sword",
      "reload": "sword"
    },
    "shotSound": "S_Whip2",
    "hitSound": "S_Cut3",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "critical": 0.4,
      "criticalDmg": 0.3,
      "noAmmo": true
    },
    "description": "Extremely sharp. Hold on to your limbs!"
  },
  {
    "type": 3,
    "id": "Saw",
    "sprite": "Saw",
    "name": "Saw",
    "typeName": "Machine Gun",
    "levelRequired": 1,
    "damage": 11,
    "force": 3,
    "splash": 0,
    "clipSize": 50,
    "clipSpare": 3,
    "range": 50,
    "recoil": 7,
    "autoFire": true,
    "shootDelay": 0.13,
    "xOffset": 10,
    "yOffset": 10,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "heavy",
      "fire": "heavy",
      "reload": "heavy"
    },
    "shotSound": "S_rifle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "RPG",
    "sprite": "RPG",
    "name": "RPG",
    "typeName": "Explosive",
    "levelRequired": 2,
    "damage": 100,
    "force": 25,
    "splash": 100,
    "clipSize": 1,
    "clipSpare": 5,
    "range": 60,
    "recoil": 7,
    "autoFire": false,
    "shootDelay": 0.9,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "explosion",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "rocket",
      "fire": "rocket",
      "reload": "rocket"
    },
    "shotSound": "S_rocketFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Basic",
    "parameters": [
      "gas_small",
      7,
      0.5
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "RPD",
    "sprite": "RPD",
    "name": "RPD",
    "typeName": "Machine Gun",
    "levelRequired": 6,
    "damage": 16,
    "force": 3,
    "splash": 0,
    "clipSize": 50,
    "clipSpare": 3,
    "range": 62,
    "recoil": 6,
    "autoFire": true,
    "shootDelay": 0.23,
    "xOffset": 10,
    "yOffset": 10,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "heavy",
      "fire": "heavy",
      "reload": "heavy"
    },
    "shotSound": "S_ak",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "Thumper",
    "sprite": "Thumper",
    "name": "Thumper",
    "typeName": "Explosive",
    "levelRequired": 8,
    "damage": 80,
    "force": 20,
    "splash": 60,
    "clipSize": 2,
    "clipSpare": 3,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "smoke",
      "hit": "explosionSmall",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "launcher",
      "fire": "launcher",
      "reload": "launcher"
    },
    "shotSound": "S_ripperFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Bounce",
    "parameters": [
      "grenade",
      3,
      4,
      1.5
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "AUG HBAR",
    "sprite": "AUG HBAR",
    "name": "AUG HBAR",
    "typeName": "Machine Gun",
    "levelRequired": 11,
    "damage": 18,
    "force": 10,
    "splash": 0,
    "clipSize": 30,
    "clipSpare": 3,
    "range": 58,
    "recoil": 2,
    "autoFire": true,
    "shootDelay": 0.18,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "bullpup",
      "fire": "bullpup",
      "reload": "bullpup"
    },
    "shotSound": "S_aug",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "Stinger",
    "sprite": "Stinger",
    "name": "Stinger",
    "typeName": "Explosive",
    "levelRequired": 14,
    "damage": 90,
    "force": 25,
    "splash": 100,
    "clipSize": 1,
    "clipSpare": 5,
    "range": 70,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.9,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "explosion",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "rocket",
      "fire": "rocket",
      "reload": "rocket"
    },
    "shotSound": "S_rocketFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Follow",
    "parameters": [
      "gas_small",
      2,
      0,
      180,
      6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "First Blood",
    "sprite": "First Blood",
    "name": "First Blood",
    "typeName": "Machine Gun",
    "levelRequired": 17,
    "damage": 17,
    "force": 3,
    "splash": 0,
    "clipSize": 50,
    "clipSpare": 3,
    "range": 52,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.1,
    "xOffset": 10,
    "yOffset": 10,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "heavy",
      "fire": "heavy",
      "reload": "heavy"
    },
    "shotSound": "S_elite",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "Lawnchair",
    "sprite": "Lawnchair",
    "name": "M-32",
    "typeName": "Explosive",
    "levelRequired": 20,
    "damage": 55,
    "force": 15,
    "splash": 50,
    "clipSize": 6,
    "clipSpare": 3,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.4,
    "xOffset": 10,
    "yOffset": -4,
    "effect": {
      "shoot": "smoke",
      "hit": "explosionSmall",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "launcher",
      "fire": "launcher",
      "reload": "sniper"
    },
    "shotSound": "S_ripperFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Bounce",
    "parameters": [
      "grenade",
      3,
      4,
      1.5
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "OICW",
    "sprite": "OICW",
    "name": "OICW",
    "typeName": "Machine Gun",
    "levelRequired": 23,
    "damage": 46,
    "force": 10,
    "splash": 0,
    "clipSize": 14,
    "clipSpare": 3,
    "range": 68,
    "recoil": 5,
    "autoFire": true,
    "shootDelay": 0.28,
    "xOffset": 10,
    "yOffset": -1,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "sniper",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "bullpup",
      "fire": "bullpup",
      "reload": "bullpup"
    },
    "shotSound": "S_deagle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      4.5,
      11202303,
      0.3,
      2.5,
      11202303,
      0.6
    ],
    "extra": {},
    "description": "An experimental weapon. Slow, but powerful."
  },
  {
    "type": 3,
    "id": "Javelin",
    "sprite": "Javelin",
    "name": "Javelin",
    "typeName": "Explosive",
    "levelRequired": 26,
    "damage": 115,
    "force": 25,
    "splash": 100,
    "clipSize": 1,
    "clipSpare": 3,
    "range": 80,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.9,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "explosion",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "rocket",
      "fire": "rocket",
      "reload": "rocket"
    },
    "shotSound": "S_rocketFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Follow",
    "parameters": [
      "gas_small",
      3,
      0,
      150,
      11
    ],
    "extra": {},
    "description": "Extremely accurate homing capabilities, but low ammo."
  },
  {
    "type": 3,
    "id": "Mini Gun",
    "sprite": "Mini Gun",
    "name": "Mini Gun",
    "typeName": "Machine Gun",
    "levelRequired": 29,
    "damage": 15,
    "force": 10,
    "splash": 0,
    "clipSize": 100,
    "clipSpare": 1,
    "range": 42,
    "recoil": 9,
    "autoFire": true,
    "shootDelay": 0.07,
    "xOffset": 10,
    "yOffset": 10,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "heavy",
      "fire": "heavy",
      "reload": "heavy"
    },
    "shotSound": "S_mp5",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 3,
    "id": "Commando",
    "sprite": "Commando",
    "name": "Commando",
    "typeName": "Explosive",
    "levelRequired": 32,
    "damage": 100,
    "force": 25,
    "splash": 100,
    "clipSize": 4,
    "clipSpare": 3,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.4,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "explosion",
      "shell": "rocket",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "rocket",
      "fire": "rocket",
      "reload": "rocket"
    },
    "shotSound": "S_rocketFire",
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Basic",
    "parameters": [
      "gas_small",
      7,
      0.5
    ],
    "extra": {},
    "description": "Can carry multiple rockets at once."
  },
  {
    "type": 4,
    "id": "M3",
    "sprite": "M3",
    "name": "Defriender",
    "typeName": "Shotgun",
    "levelRequired": 1,
    "damage": 12,
    "force": 10,
    "splash": 0,
    "clipSize": 4,
    "clipSpare": 3,
    "range": 34,
    "recoil": 9,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "shotgun",
      "fire": "shotgun",
      "reload": "shotgun"
    },
    "shotSound": "S_shotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "Riot",
    "sprite": "Riot",
    "name": "Riot",
    "typeName": "Shield",
    "levelRequired": 2,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0.1,
      "reduce": 0.2,
      "useSecondary": true,
      "halfAim": true
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "AA 12",
    "sprite": "AA 12",
    "name": "AA 12",
    "typeName": "Shotgun",
    "levelRequired": 6,
    "damage": 6,
    "force": 10,
    "splash": 0,
    "clipSize": 8,
    "clipSpare": 3,
    "range": 28,
    "recoil": 9,
    "autoFire": true,
    "shootDelay": 0.25,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "shotgun",
      "fire": "shotgun",
      "reload": "rifle"
    },
    "shotSound": "S_autoshotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "Police",
    "sprite": "Police",
    "name": "Police",
    "typeName": "Shield",
    "levelRequired": 8,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0.05,
      "reduce": 0.3,
      "useSecondary": true,
      "halfAim": true
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "SPAS 12",
    "sprite": "SPAS 12",
    "name": "SPAS 12",
    "typeName": "Shotgun",
    "levelRequired": 11,
    "damage": 15,
    "force": 10,
    "splash": 0,
    "clipSize": 7,
    "clipSpare": 3,
    "range": 40,
    "recoil": 9,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "shotgun",
      "fire": "shotgun",
      "reload": "shotgun"
    },
    "shotSound": "S_shotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "Blast",
    "sprite": "Blast",
    "name": "Blast",
    "typeName": "Shield",
    "levelRequired": 14,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0,
      "reduce": 0.25,
      "useSecondary": true,
      "halfAim": true,
      "resist": 0.3
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "Striker",
    "sprite": "Striker",
    "name": "Striker",
    "typeName": "Shotgun",
    "levelRequired": 17,
    "damage": 13,
    "force": 10,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 3,
    "range": 30,
    "recoil": 9,
    "autoFire": false,
    "shootDelay": 0.3,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "rifle",
      "fire": "rifle",
      "reload": "sniper"
    },
    "shotSound": "S_autoshotgunFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": ""
  },
  {
    "type": 4,
    "id": "Pointy",
    "sprite": "Pointy",
    "name": "Buckler",
    "typeName": "Shield",
    "levelRequired": 20,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0,
      "reduce": 0.2,
      "useSecondary": true
    },
    "description": "Very lightweight. Allows for great accuracy while blocking."
  },
  {
    "type": 4,
    "id": "Judgement",
    "sprite": "Judgement",
    "name": "Judgement",
    "typeName": "Shotgun",
    "levelRequired": 23,
    "damage": 15,
    "force": 10,
    "splash": 0,
    "clipSize": 4,
    "clipSpare": 3,
    "range": 52,
    "recoil": 5,
    "autoFire": false,
    "shootDelay": 0.5,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "shotgun",
      "fire": "shotgun",
      "reload": "shotgun"
    },
    "shotSound": "S_sniper",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": "They won't be back."
  },
  {
    "type": 4,
    "id": "Meat",
    "sprite": "Meat",
    "name": "Meat",
    "typeName": "Shield",
    "levelRequired": 26,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0,
      "reduce": 0.45,
      "useSecondary": true,
      "halfAim": true
    },
    "description": "Pleased to meat you."
  },
  {
    "type": 4,
    "id": "Omar",
    "sprite": "Omar",
    "name": "Omar",
    "typeName": "Shotgun",
    "levelRequired": 29,
    "damage": 25,
    "force": 10,
    "splash": 0,
    "clipSize": 2,
    "clipSpare": 3,
    "range": 30,
    "recoil": 9,
    "autoFire": false,
    "shootDelay": 0.1,
    "xOffset": 10,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "shotgun",
      "hudBullet": "shotgun"
    },
    "animation": {
      "idle": "launcher",
      "fire": "launcher",
      "reload": "launcher"
    },
    "shotSound": "S_deagle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "vision": 0.3,
      "extraShots": 4
    },
    "description": "Double barrel means extremely fast firing speed, but only 2 rounds."
  },
  {
    "type": 4,
    "id": "Siegius",
    "sprite": "Siegius",
    "name": "Siegius",
    "typeName": "Shield",
    "levelRequired": 32,
    "damage": 0,
    "force": 3,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "shield",
      "fire": "shield",
      "reload": "shield"
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "reflect": 0.3,
      "reduce": 0.1,
      "useSecondary": true,
      "halfAim": true
    },
    "description": "Provides little defense, but is extremely effective at reflecting attacks."
  },
  {
    "type": 5,
    "id": "poison",
    "sprite": "poison",
    "name": "Poison",
    "typeName": "",
    "levelRequired": 0,
    "damage": 0,
    "force": 0,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": null,
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "curse",
    "sprite": "curse",
    "name": "Vampire Curse",
    "typeName": "",
    "levelRequired": 0,
    "damage": 0,
    "force": 0,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": null,
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "env",
    "sprite": "env",
    "name": "Environment",
    "typeName": "",
    "levelRequired": 0,
    "damage": 0,
    "force": 0,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": null,
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "env2",
    "sprite": "env2",
    "name": "Environment",
    "typeName": "",
    "levelRequired": 0,
    "damage": 0,
    "force": 0,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": null,
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "env3",
    "sprite": "env3",
    "name": "Environment",
    "typeName": "",
    "levelRequired": 0,
    "damage": 0,
    "force": 0,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 0,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 1,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": null,
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "heli",
    "sprite": "heli",
    "name": "Helicopter",
    "typeName": "",
    "levelRequired": 1,
    "damage": 18,
    "force": 3,
    "splash": 0,
    "clipSize": 12,
    "clipSpare": 3,
    "range": 70,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.3,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "gas_small",
      "shell": "pistol",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": "S_uziFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "airs",
    "sprite": "airs",
    "name": "Air Strike",
    "typeName": "Explosive",
    "levelRequired": 1,
    "damage": 300,
    "force": 25,
    "splash": 140,
    "clipSize": 3,
    "clipSpare": 3,
    "range": 300,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.15,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "explosion",
      "shell": "rocket",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Basic",
    "parameters": [
      "gas_small",
      7,
      0.5
    ],
    "extra": {
      "noAllyDmg": true
    },
    "description": ""
  },
  {
    "type": 5,
    "id": "bomb",
    "sprite": "bomb",
    "name": "Martyrdom",
    "typeName": "Explosive",
    "levelRequired": 1,
    "damage": 150,
    "force": 25,
    "splash": 100,
    "clipSize": 2,
    "clipSpare": 3,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.15,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "explosion",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Splash",
    "parameters": [
      true
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "fire",
    "sprite": "fire",
    "name": "Combustion",
    "typeName": "Explosive",
    "levelRequired": 1,
    "damage": 12,
    "force": 3,
    "splash": 150,
    "clipSize": 2,
    "clipSpare": 3,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.15,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Splash",
    "parameters": [
      false
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "none",
    "sprite": "none",
    "name": "No Weapon",
    "typeName": "",
    "levelRequired": 1,
    "damage": 9,
    "force": 3,
    "splash": 150,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.15,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": null,
    "bulletClass": "Bullet_Splash",
    "parameters": [
      false
    ],
    "extra": {
      "vision": 0.0001,
      "noShoot": true
    },
    "description": ""
  },
  {
    "type": 5,
    "id": "mine",
    "sprite": "mine",
    "name": "Bouncing Betty",
    "typeName": "",
    "levelRequired": 1,
    "damage": 150,
    "force": 15,
    "splash": 140,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 60,
    "recoil": 6,
    "autoFire": false,
    "shootDelay": 0.15,
    "xOffset": 0,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "explosion",
      "shell": "",
      "hudBullet": ""
    },
    "animation": {
      "idle": "",
      "fire": "",
      "reload": ""
    },
    "shotSound": null,
    "hitSound": "S_rocketExplode",
    "bulletClass": "Bullet_Proj_Mine",
    "parameters": [],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "USP2",
    "sprite": "USP",
    "name": "USP",
    "typeName": "Pistol",
    "levelRequired": 1,
    "damage": 15,
    "force": 3,
    "splash": 0,
    "clipSize": 1,
    "clipSpare": 0,
    "range": 66,
    "recoil": 3,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 8,
    "yOffset": -8,
    "effect": {
      "shoot": "smoke",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_pistolFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {
      "noAmmo": true
    },
    "description": ""
  },
  {
    "type": 5,
    "id": "Saw2",
    "sprite": "Saw",
    "name": "Saw",
    "typeName": "Machine Gun",
    "levelRequired": 1,
    "damage": 11,
    "force": 3,
    "splash": 0,
    "clipSize": 50,
    "clipSpare": 100,
    "range": 50,
    "recoil": 7,
    "autoFire": true,
    "shootDelay": 0.13,
    "xOffset": 10,
    "yOffset": 10,
    "effect": {
      "shoot": "gas_small",
      "hit": "bulletspark",
      "shell": "pistol",
      "hudBullet": "machine"
    },
    "animation": {
      "idle": "heavy",
      "fire": "heavy",
      "reload": "heavy"
    },
    "shotSound": "S_rifle",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      true,
      3.5,
      16777156,
      0.3,
      1.5,
      16777156,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "Golden Gun",
    "sprite": "Golden Gun",
    "name": "Golden Gun",
    "typeName": "Pistol",
    "levelRequired": 1,
    "damage": 500,
    "force": 20,
    "splash": 0,
    "clipSize": 1,
    "clipSpare": 15,
    "range": 70,
    "recoil": 0,
    "autoFire": false,
    "shootDelay": 0.4,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "gas_small",
      "hit": "gas_small",
      "shell": "pistol",
      "hudBullet": "pistol"
    },
    "animation": {
      "idle": "pistol",
      "fire": "pistol",
      "reload": "pistol"
    },
    "shotSound": "S_sniperFire",
    "hitSound": null,
    "bulletClass": "Bullet_Line_Basic",
    "parameters": [
      false,
      3.5,
      16750899,
      0.3,
      1.5,
      16764006,
      0.6
    ],
    "extra": {},
    "description": ""
  },
  {
    "type": 5,
    "id": "Butter Knife",
    "sprite": "Butter Knife",
    "name": "Butter Knife",
    "typeName": "Melee",
    "levelRequired": 1,
    "damage": 500,
    "force": 2,
    "splash": 0,
    "clipSize": 0,
    "clipSpare": 0,
    "range": 8,
    "recoil": 2,
    "autoFire": false,
    "shootDelay": 0.25,
    "xOffset": 6,
    "yOffset": 0,
    "effect": {
      "shoot": "",
      "hit": "",
      "shell": "",
      "hudBullet": "rocket"
    },
    "animation": {
      "idle": "knife",
      "fire": "knife",
      "reload": "knife"
    },
    "shotSound": "S_Whip1",
    "hitSound": "S_Cut3",
    "bulletClass": "Bullet_Melee_Basic",
    "parameters": [],
    "extra": {
      "vision": 0.3,
      "noAmmo": true
    },
    "description": ""
  }
]);
