// GENERATED from assets/reverse/ffdec-deep-20260720/scripts/Stats_Skills.as.
// Regenerate with: npm run generate:skills
export const SOURCE_SKILLS = Object.freeze([
  {
    "classNumber": 0,
    "id": "blur2",
    "sprite": "blur",
    "name": "Blur",
    "typeName": "Timed",
    "cost": 0,
    "levelRequired": 1,
    "value": 10,
    "special": "Dodge all attacks when below 30% health",
    "description": "When low on health, the Assassin will dodge all attacks for 3 seconds.\n\n(Can only occur once every 30 seconds)"
  },
  {
    "classNumber": 0,
    "id": "shadow2",
    "sprite": "shadow",
    "name": "Shadow Blend",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 1,
    "value": 0.5,
    "special": "Become invisible while crouching\nMelee attacks get +50% critical when invisible",
    "description": "By crouching and moving slowly, you're able to blend into the shadows, unable to be seen.\n\n(Attacking or being attacked will reveal you)"
  },
  {
    "classNumber": 1,
    "id": "none",
    "sprite": "none",
    "name": "None",
    "typeName": "None",
    "cost": 0,
    "levelRequired": 1,
    "value": -1,
    "special": "",
    "description": "No skill equipped."
  },
  {
    "classNumber": 1,
    "id": "combat",
    "sprite": "mastery",
    "name": "Combat Mastery",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 2,
    "value": -1,
    "special": "+3% Critical\n+3% Aim\n+10% Ammo\n+10 Hp",
    "description": "Being a jack of all trades, the Medic is adept at all forms of combat."
  },
  {
    "classNumber": 1,
    "id": "regen",
    "sprite": "regen",
    "name": "Regenerative Tissue",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 4,
    "value": -1,
    "special": "Immediate health regeneration",
    "description": "After years in the field, the Medic's body tissue is so used to being healed that it is now always renegerating itself automatically."
  },
  {
    "classNumber": 1,
    "id": "charisma",
    "sprite": "charisma",
    "name": "Charismatic",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 10,
    "value": -1,
    "special": "All killstreaks require 1 less kill",
    "description": "The Medic is a friend to all. Because of this, battle assistance comes to his aid quicker than others."
  },
  {
    "classNumber": 1,
    "id": "operation",
    "sprite": "operation",
    "name": "Self Revive",
    "typeName": "Timed",
    "cost": 0,
    "levelRequired": 16,
    "value": 30,
    "special": "When about to die, heal 50% health",
    "description": "After reaching 0 health, the Medic performs a last second operation on himself, regaining half of his health.\n\n(Can only occur once every 30 seconds)"
  },
  {
    "classNumber": 2,
    "id": "none",
    "sprite": "none",
    "name": "None",
    "typeName": "None",
    "cost": 0,
    "levelRequired": 1,
    "value": -1,
    "special": "",
    "description": "No skill equipped."
  },
  {
    "classNumber": 2,
    "id": "critical",
    "sprite": "mastery",
    "name": "Focus Mastery",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 2,
    "value": 0.05,
    "special": "+5% Critical\n+5% Aim",
    "description": "Extreme focus allows you to hone your aim and target enemy weakpoints."
  },
  {
    "classNumber": 2,
    "id": "vital",
    "sprite": "vital",
    "name": "Vital Sight",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 4,
    "value": 0.25,
    "special": "Criticals and Headshots do +25% damage",
    "description": "Adds a laser sight to the weapon, allowing you to pinpoint enemy weakpoints."
  },
  {
    "classNumber": 2,
    "id": "shadow",
    "sprite": "shadow",
    "name": "Shadow Blend",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 10,
    "value": 0.5,
    "special": "Become invisible while crouching\nMelee attacks get +50% critical when invisible",
    "description": "By crouching and moving slowly, the Assassin is able to blend into the shadows, unable to be seen.\n\n(Attacking or being attacked will reveal you)"
  },
  {
    "classNumber": 2,
    "id": "blur",
    "sprite": "blur",
    "name": "Blur",
    "typeName": "Timed",
    "cost": 0,
    "levelRequired": 16,
    "value": 30,
    "special": "Dodge all attacks when below 30% health",
    "description": "When low on health, the Assassin will dodge all attacks for 2 seconds.\n\n(Can only occur once every 30 seconds)"
  },
  {
    "classNumber": 3,
    "id": "none",
    "sprite": "none",
    "name": "None",
    "typeName": "None",
    "cost": 0,
    "levelRequired": 1,
    "value": -1,
    "special": "",
    "description": "No skill equipped."
  },
  {
    "classNumber": 3,
    "id": "ammo",
    "sprite": "mastery",
    "name": "Ammo Mastery",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 2,
    "value": 0.2,
    "special": "+20% Ammo",
    "description": "All those extra pockets and slots aren't just for show."
  },
  {
    "classNumber": 3,
    "id": "resist",
    "sprite": "resist",
    "name": "Flame Resistance",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 4,
    "value": 0.6,
    "special": "-40% explosive damage",
    "description": "Years of explosive training has conditioned the Commando to resist all explosives. No one knows how."
  },
  {
    "classNumber": 3,
    "id": "clip",
    "sprite": "clip",
    "name": "Ammo Feed",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 10,
    "value": -1,
    "special": "Never reload with a machine gun",
    "description": "Instead of clips, the Commando feeds all his ammo directly into the gun so he never needs to reload.\n\n(Machine guns only)"
  },
  {
    "classNumber": 3,
    "id": "bomb",
    "sprite": "bomb",
    "name": "Martyrdom",
    "typeName": "Timed",
    "cost": 0,
    "levelRequired": 16,
    "value": 30,
    "special": "Explode on death",
    "description": "Rigging himself with explosives, the Commando will explode on death, taking out all nearby enemies with him.\n\n(Can only occur every 30 seconds)"
  },
  {
    "classNumber": 4,
    "id": "none",
    "sprite": "none",
    "name": "None",
    "typeName": "None",
    "cost": 0,
    "levelRequired": 1,
    "value": -1,
    "special": "",
    "description": "No skill equipped."
  },
  {
    "classNumber": 4,
    "id": "health",
    "sprite": "mastery",
    "name": "Armor Mastery",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 2,
    "value": 20,
    "special": "+20 Hp",
    "description": "When it comes to bullets, the Tank can never have too much protection."
  },
  {
    "classNumber": 4,
    "id": "adren",
    "sprite": "adren",
    "name": "Adrenaline",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 4,
    "value": 3,
    "special": "3x Hp regeneration",
    "description": "When in danger, the Tank gets a surge of Adrenaline, recovering his health extremely fast."
  },
  {
    "classNumber": 4,
    "id": "iron",
    "sprite": "iron",
    "name": "Full Protection",
    "typeName": "Passive",
    "cost": 0,
    "levelRequired": 10,
    "value": 0.85,
    "special": "Reduce all damage by 15% when using a shield",
    "description": "When using a shield, the Tank becomes one with the it, allowing the unprotected parts of his body to reduce some damage as well.\n\n(Requires Shield)"
  },
  {
    "classNumber": 4,
    "id": "will",
    "sprite": "fist",
    "name": "Iron Will",
    "typeName": "Timed",
    "cost": 0,
    "levelRequired": 16,
    "value": 5,
    "special": "Reduce next attack by 70%",
    "description": "Every once in a while, the Tank can reduce the next damage he takes by 70%.\n\n(Can only occur once every 5 seconds)"
  }
]);
